"use client";

import { useState } from "react";
import Image from "next/image";
import { ArrowLeft, ArrowRight, BookOpen, Briefcase, Building2, Code2, GraduationCap, Heart, Lightbulb, Music2, Palette, PenLine, Rocket, Search, Sparkles, UserRound, Wrench } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { emptyProfile, roleOptions, useOptions, type QuatreProfile } from "@/lib/profile";

const roleIcons: LucideIcon[] = [GraduationCap, Rocket, Briefcase, Sparkles, Code2, Palette, Music2, Palette, Search, Sparkles, BookOpen, Building2, UserRound, PenLine, Lightbulb, PenLine, Wrench];
const useIcons: LucideIcon[] = [Briefcase, BookOpen, Building2, Search, Code2, PenLine, Palette, Lightbulb, UserRound, Rocket, GraduationCap, Heart, Sparkles];

export function Onboarding({ initialProfile, onComplete, onSkip }: { initialProfile: QuatreProfile; onComplete: (profile: QuatreProfile) => void; onSkip: () => void }) {
  const [step, setStep] = useState(0);
  const [profile, setProfile] = useState<QuatreProfile>({ ...emptyProfile, ...initialProfile });
  const toggle = (field: "roles" | "usageInterests", value: string) => setProfile((current) => ({ ...current, [field]: current[field].includes(value) ? current[field].filter((item) => item !== value) : [...current[field], value] }));
  return <section className="onboarding-screen" aria-labelledby="onboarding-title">
    <header className="onboarding-header"><a className="onboarding-brand" href="#workspace"><Image src="/icon.svg" alt="" width={34} height={34} priority/><span>quatre</span></a><button className="onboarding-skip" onClick={onSkip}>Skip for now</button></header>
    <div className="onboarding-progress" aria-label={"Step " + Math.max(step, 1) + " of 4"}>{[0, 1, 2, 3].map((item) => <span key={item} className={step >= item ? "progress-active" : ""}/>)}</div>
    <div className="onboarding-stage" key={step}>
      {step === 0 && <div className="onboarding-welcome"><span className="onboarding-emblem"><Image src="/icon.svg" alt="" width={34} height={34} priority/></span><p className="eyebrow">INTELLIGENCE, IN CONCERT</p><h1 id="onboarding-title">Welcome to<br/><span>Quatre.</span></h1><p>One thoughtful place to ask, compare perspectives, and make sense of what matters to you.</p><button className="onboarding-primary" onClick={() => setStep(1)}>Get started <ArrowRight size={16}/></button><small>A few quick choices. You can change them anytime.</small></div>}
      {step === 1 && <div className="onboarding-choice"><p className="eyebrow">A LITTLE ABOUT YOU Â· 01</p><h1 id="onboarding-title">What brings<br/>you here?</h1><p className="onboarding-subtitle">Choose any that feel like you. This helps us make Quatre more useful.</p><div className="choice-grid">{roleOptions.map((item, index) => { const Icon = roleIcons[index]; const selected = profile.roles.includes(item); return <button key={item} className={"choice-option " + (selected ? "choice-selected" : "")} aria-pressed={selected} onClick={() => toggle("roles", item)}><Icon size={18} strokeWidth={1.7}/><span>{item}</span>{selected && <i aria-hidden="true"/>}</button>; })}</div><div className="onboarding-nav"><button className="onboarding-back" onClick={() => setStep(0)}><ArrowLeft size={15}/> Back</button><button className="onboarding-primary" onClick={() => setStep(2)}>Continue <ArrowRight size={16}/></button></div></div>}
      {step === 2 && <div className="onboarding-choice"><p className="eyebrow">YOUR EVERYDAY Â· 02</p><h1 id="onboarding-title">What will you<br/>use Quatre for?</h1><p className="onboarding-subtitle">Pick a few. Your choices stay private unless you choose to share them.</p><div className="choice-grid">{useOptions.map((item, index) => { const Icon = useIcons[index]; const selected = profile.usageInterests.includes(item); return <button key={item} className={"choice-option " + (selected ? "choice-selected" : "")} aria-pressed={selected} onClick={() => toggle("usageInterests", item)}><Icon size={18} strokeWidth={1.7}/><span>{item}</span>{selected && <i aria-hidden="true"/>}</button>; })}</div><div className="onboarding-nav"><button className="onboarding-back" onClick={() => setStep(1)}><ArrowLeft size={15}/> Back</button><button className="onboarding-primary" onClick={() => setStep(3)}>Continue <ArrowRight size={16}/></button></div></div>}
      {step === 3 && <div className="onboarding-choice onboarding-profile"><p className="eyebrow">MAKE QUATRE YOURS Â· 03</p><h1 id="onboarding-title">A name to<br/>call you by.</h1><p className="onboarding-subtitle">Add only what youâ€™re comfortable sharing. You can fill in the rest later.</p><div className="onboarding-fields"><label>Display name<input autoComplete="name" maxLength={80} value={profile.displayName} onChange={(event) => setProfile((current) => ({ ...current, displayName: event.target.value }))} placeholder="Your name"/></label><label>Username <span>optional</span><input autoComplete="username" maxLength={24} pattern="[A-Za-z0-9_]{3,24}" value={profile.username} onChange={(event) => setProfile((current) => ({ ...current, username: event.target.value.replace(/[^A-Za-z0-9_]/g, "") }))} placeholder="yourname"/></label><label>What are you working on? <span>optional</span><textarea maxLength={240} value={profile.bio} onChange={(event) => setProfile((current) => ({ ...current, bio: event.target.value }))} placeholder="A sentence or two about you" rows={3}/></label><label className="onboarding-share"><span><b>Show me in Community</b><small>Your profile stays private until you opt in.</small></span><input type="checkbox" checked={profile.communityVisible} onChange={(event) => setProfile((current) => ({ ...current, communityVisible: event.target.checked }))}/></label></div><div className="onboarding-nav"><button className="onboarding-back" onClick={() => setStep(2)}><ArrowLeft size={15}/> Back</button><button className="onboarding-primary" onClick={() => onComplete(profile)}>Enter Quatre <ArrowRight size={16}/></button></div></div>}
    </div>
    <footer className="onboarding-footer"><Sparkles size={14}/> Your interests and profile are yours to control.</footer>
  </section>;
}


